### ISSUE TITLE
'ledcSetup' was not declared in this scope

### ISSUE THREAD

**Issue by mdmbct** [RoboticsBrno/ServoESP32#16]
I use this lib in PlatformIO for CLion, but the console print these msgs shown in the img after PlatformIO build.
![image](https://user-images.githubusercontent.com/32732204/140634834-cee46877-924e-4d7d-a611-2a0c15e156e1.png)
So I clone this repository, and also can not find the methods was not declared.

**Comment by JarekParal** [comment]
Hi, the `ledcXY` methods should be part of the Arduino ESP32 framework included with `#include "Arduino.h"`. Could you check that the framework is properly configured? 
Could you also copy/paste the whole build log?
We are using Platform.io mainly in VSCode. I don't know if you need to do something special in CLion to make it work. Please also share your `platformio.ini` file.

**Comment by mdmbct** [comment]
> Hi, the `ledcXY` methods should be part of the Arduino ESP32 framework included with `#include "Arduino.h"`. Could you check that the framework is properly configured? Could you also copy/paste the whole build log? We are using Platform.io mainly in VSCode. I don't know if you need to do something special in CLion to make it work. Please also share your `platformio.ini` file.

As a beginner, I didn't distinguish the esp32 and esp8266🥲. The lib is for esp32 but my dk is esp8266🤦‍♂️🤦‍♂️.
