### ISSUE TITLE
Compatibility with Seeed Studio XIAO ESP32C3

### ISSUE THREAD

**Issue by RalfStehle** [RoboticsBrno/ServoESP32#20]
Unfortunately, I am unable to control a servo on the Seeed Studio XIAO ESP32C3.

**Comment by JarekParal** [comment]
It could be a similar issue as it is described in #18

**Comment by JarekParal** [comment]
It should be solved in https://github.com/RoboticsBrno/ServoESP32/releases/tag/v1.1.0

Discussed in #23 PR.
