### ISSUE TITLE
code doesn't load because already have a Servo library

### ISSUE THREAD

**Issue by FurkanEfe29** [RoboticsBrno/ServoESP32#28]
![resim_2023-11-09_000320080](https://github.com/RoboticsBrno/ServoESP32/assets/125969609/dc261c1d-3a82-4759-8a82-4266ca2ce3d2)

When you write it like "#include <Servo.h>", it conflicts with the other library, so ı can't load the code on my esp32.

**Comment by JarekParal** [comment]
@FurkanEfe29 Can you share more info about your Arduino IDE version, ServoESP32 version and how you install the ServoESP32 library to the IDE?

**Comment by FurkanEfe29** [comment]
I'm using 2.2.1 version of arduino IDE and the last version of Servo Library (1.1.1 version). I install with library menu in the Arduino IDE.

**Comment by JarekParal** [comment]
Could you try to downgrade the ServoESP32 library to `v1.0.3`? This seems to be a temporary workaround. There is an issue #26 which probably caused your error.

**Comment by FurkanEfe29** [comment]
Downgrading is worked. Now I can drive my servo motors at version 1.0.3. Thank you.
